### ISSUE TITLE
Convert to Simple Darwin Core

### ISSUE THREAD

**Issue by JWCook** [JWCook/pyinaturalist-convert#7]
Continued from https://github.com/niconoe/pyinaturalist/issues/143

### Tasks
This is currently about 80% done, and the most relevant DwC terms are currently working. Things left to do:

- [x] Add remaining observation fields (about 11 fields noted in code comments)
- [x] Add remaining photo fields (for `eol:dataObject`; about 7 fields noted in code comments)
- [x] Formatting functions (for values derived from JSON fields but in a different format)
- [x] Set observation fields that map to multiple DwC terms (like `uri --> dcterms:references, dwc:occurrenceDetails`)
- [x] Include metadata for all observation photos (currently just using the first photo)
- [x] Add XML namespaces
- [x] Support converting a list of observations to a single `SimpleDarwinRecordSet` with multiple `SimpleDarwinRecord` objects
- [x] Unit tests
- [x] Documentation (just a simple usage example is fine for now)

### Usage
When this is complete, I expect the usage will look something like:
```python
from pyinaturalist import get_observations
from pyinaturalist_convert import to_dwc

observations = get_observations(user_id='my_username')
to_dwc(observations, 'my_observations.dwc')
```

### Example observations
For reference:
* Observation JSON (from `node_api.get_observations()`): [obs_45524803.json](https://github.com/niconoe/pyinaturalist/blob/dwc/examples/sample_data/obs_45524803.json)
* The same observation in DwC format (from `rest_api.get_observations()`): [obs_45524803.dwc](https://github.com/niconoe/pyinaturalist/blob/dwc/examples/sample_data/obs_45524803.dwc)
* Current draft of `pyinaturalist-convert` output: [test/sample_data/observations.dwc](https://github.com/JWCook/pyinaturalist-convert/blob/main/test/sample_data/observations.dwc)

**Comment by JWCook** [comment]
@FelipeSBarros I made a bit more progress on this, and added some notes for remaining tasks. I'll keep working on this when I have time, and you can pick up any of these tasks too if you'd like. [Here's an example](https://github.com/JWCook/pyinaturalist-convert/blob/main/test/sample_data/observations.dwc) of what the output currently looks like.

**Comment by FelipeSBarros** [comment]
@JWCook that's great. I will definitely take a look on those tasks to see how can I contribute.
This week and the next will be a littlebit hard todo it, but it is already in my agenda to get back on this colaboration.

**Comment by FelipeSBarros** [comment]
Hey, @JWCook ! Hope everything is fine with you...
I am finishing the system I have told you and I just realized that  have to consider the pagination of the results from `get_observations`. Looking the documentation I found the pagination module: [`pyinaturalist.pagination.paginate_all(api_func, *args, method='page', **params)](https://pyinaturalist.readthedocs.io/en/v0.13.0/modules/pyinaturalist.pagination.html#pyinaturalist.pagination.paginate_all) .
I am wondering if this is the correct approach and if it is, how to use it?
Thanks in advance
Felipe

**Comment by JWCook** [comment]
All you need to do is pass `page='all'`, for example:
```python
get_observations(project_id=1234 page='all')
```

There is some more info in the [GeneralUsage](https://pyinaturalist.readthedocs.io/en/v0.13.0/general_usage.html#pagination) section of the docs.

**Comment by FelipeSBarros** [comment]
>get_observations(project_id=1234, page='all')

I am getting a 400 response error. Should I be loged in to do such request?
`all_pages = get_observations(project_id=105820, page='all')`
```
 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.inaturalist.org/v1/observations?project_id=105820&page=all&only_id=false
```

**Comment by JWCook** [comment]
Which version of pyinaturalist are you using? That feature was added in the latest release (`0.13`).

**Comment by FelipeSBarros** [comment]
>Which version of pyinaturalist are you using? That feature was added in the latest release (0.13).
Thanks, @JWCook ! ...and I am sorry for such dumb questions I have made. 
I was using 0.12. All working fine with latest version.

**Comment by JWCook** [comment]
Good! 

And those aren't dumb questions at all. I want to make these things easy to use, so it's useful to know which parts are potentially confusing.

**Comment by FelipeSBarros** [comment]
Hey @JWCook, sorry leaving you alone on this issue. I am using the hacktoberfest to get back on collaborations.
Let me know if there is any task you think I should prioritize.
Best regards
